apiVersion: v1
kind: Service
metadata:
  labels:
    name: apiman-gateway
  name: apiman-gateway
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
    - port: 443
      name: https
      targetPort: 8443
  selector:
    app: apiman-gateway
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: apiman-gateway
  name: apiman-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apiman-gateway
    spec:
      containers:
        - name: apiman-gateway
          image: youngkoss/apiman:g1.2.9.Final
          imagePullPolicy: Always
          env:
          - name: POSTGRES_DATABASE
            value: apiman-gateway   
          - name: POSTGRES_USER
            value: apiman-gateway 
          - name: POSTGRES_PASSWORD
            value: apiman-gatewayk
          - name: POSTGRES_PORT_5432_TCP_ADDR
            value: ‘localhost’
          - name: POSTGRES_PORT_5432_TCP_PORT
            value: ‘5432’
          - name: GATEWAY_ADDRESS
            value: http://apiman-gateway:8443/apiman-gateway/
          ports:
            - containerPort: 8080
              name: apiman-gateway
      
        - name: postgres
          image: postgres:9.4
          imagePullPolicy: Always
          ports:
          - containerPort: 5432
            name: apiman-gateway
          env:
              - name: POSTGRES_USER
                value: apiman-gateway
              - name: POSTGRES_PASSWORD
                value: apiman-gateway
              - name: POSTGRES_DB
                value: apiman-gateway
              - name: PGDATA
                value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: p0-pd-apiman
              mountPath: /var/lib/postgresql/data
      volumes:
      - name: p0-pd-apiman
        persistentVolumeClaim:
              claimName: els-client-pv-claim
      