apiman-gateway-db:
    image: webalexx/apiman-postgres:postgres
    environment:
      - POSTGRES_DB=apiman_gateway
      - POSTGRES_USER=apiman
      - POSTGRES_PASSWORD=apiman
      - PGDATA = /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
      
      
keyloack:
    image: webalexx/apiman-postgres:keycloak
    environment:
      - POSTGRES_DATABASE=apiman_gateway
      - POSTGRES_USER=apiman      
      - POSTGRES_PASSWORD=apiman
      - KEYCLOAK_LOGLEVEL=DEBUG
      - POSTGRES_PORT_5432_TCP_ADDR = 192.168.99.100
      - POSTGRES_PORT_5432_TCP_PORT = 5432
    links:
      - apiman-gateway-db
    ports:
      - "8082:8080"  
      

apiman:
    image: youngkoss/apiman:m.1.2.9.Final
    environment:
      - POSTGRES_DATABASE=apiman_gateway
      - POSTGRES_USER=apiman      
      - POSTGRES_PASSWORD=apiman
      - KEYCLOAK_LOGLEVEL=DEBUG
      - POSTGRES_PORT_5432_TCP_ADDR = 192.168.99.100
      - POSTGRES_PORT_5432_TCP_PORT = 5432
    links:
      - apiman-gateway-db
      - keyloack
    ports:
      - "8081:8080"


elastic: 
    image: elasticsearch
    ports:
     - "9200:9200"

      
apiman-gateway:
    image: webalexx/apiman-postgres:apiman-gateway
    environment:
      - POSTGRES_DATABASE="apiman_gateway"
      - POSTGRES_USER="apiman"      
      - POSTGRES_PASSWORD="apiman"
      - POSTGRES_PORT_5432_TCP_ADDR = "192.168.99.100"
      - POSTGRES_PORT_5432_TCP_PORT = 5432
      - KEYCLOAK_LOGLEVEL=DEBUG
      - GATEWAY_ADDRESS=http://192.168.99.100:8080/apiman-gateway
      - KEYCLOAK_ADDRESS=https://192.168.99.100:8443/auth
      - ELASTIC_ADDRESS=localhost
    links:
      - apiman-gateway-db:apiman-gateway-db
      - elastic:elastic
      - keyloack
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8443:443"
      - "443:443"
      - "8787:8787"

