apiman-gateway-db:
    image: webalexx/apiman-postgres:postgres
    environment:
      - POSTGRES_DB=apiman_gateway
      - POSTGRES_USER=apiman
      - POSTGRES_PASSWORD=apiman
      - POSTGRES_ROOT_PASSWORD=apiman
      - PGDATA = /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
      
      
keyloack:
    image: webalexx/apiman-postgres:keycloak
    environment:
      - POSTGRES_DATABASE=apiman_gateway
      - POSTGRES_USER=apiman      
      - POSTGRES_PASSWORD=apiman
      - POSTGRES_PORT_5432_TCP_ADDR=172.17.0.2
      - POSTGRES_PORT_5432_TCP_PORT=5432
        
    links:
      - apiman-gateway-db
    ports:
      - "8080:8080"  
      

