apiVersion: v1
kind: Service
metadata:
  labels:
    name: keycloak
  name: keycloak
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres
  name: postgres
spec:
  ports:
    - port: 5432
      name: http
      targetPort: 5432
  selector:
    app: postgres    
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: webalexx/keyloack
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: keycloak
          env:
              - name: POSTGRES_DATABASE
                value: keycloak   
              - name: POSTGRES_USER
                value: keycloak 
              - name: POSTGRES_PASSWORD
                value: keycloak
              - name: KEYCLOAK_LOGLEVEL
                value: ‘DEBUG’
              - name: POSTGRES_PORT_5432_TCP_ADDR
                value: ‘localhost’
              - name: POSTGRES_PORT_5432_TCP_PORT
                value: ‘5432’
        - name: postgres
          image: postgres:9.4
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: keycloak
          env:
              - name: POSTGRES_USER
                value: keycloak
              - name: POSTGRES_PASSWORD
                value: keycloak
              - name: POSTGRES_DB
                value: keycloak
              - name: PGDATA
                value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: p0-pd-apiman
              mountPath: /var/lib/postgresql/data
      volumes:
      - name: p0-pd-apiman
        persistentVolumeClaim:
              claimName: els-client-pv-claim
